version: 0.2

phases:
  install:
    commands:
      - cd lambda
      - npm install
  build:
    commands:
      - npm run build
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - index.js
    - node_modules/**/*
  base-directory: lambda
